
package com.svc32.hws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWebServiceServerImplService", targetNamespace = "http://hws.svc32.com/", wsdlLocation = "http://localhost:1986/svc32/hws/hello?wsdl")
public class HelloWebServiceServerImplService
    extends Service
{

    private final static URL HELLOWEBSERVICESERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWEBSERVICESERVERIMPLSERVICE_EXCEPTION;
    private final static QName HELLOWEBSERVICESERVERIMPLSERVICE_QNAME = new QName("http://hws.svc32.com/", "HelloWebServiceServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1986/svc32/hws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWEBSERVICESERVERIMPLSERVICE_WSDL_LOCATION = url;
        HELLOWEBSERVICESERVERIMPLSERVICE_EXCEPTION = e;
    }

    public HelloWebServiceServerImplService() {
        super(__getWsdlLocation(), HELLOWEBSERVICESERVERIMPLSERVICE_QNAME);
    }

    public HelloWebServiceServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWEBSERVICESERVERIMPLSERVICE_QNAME, features);
    }

    public HelloWebServiceServerImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWEBSERVICESERVERIMPLSERVICE_QNAME);
    }

    public HelloWebServiceServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWEBSERVICESERVERIMPLSERVICE_QNAME, features);
    }

    public HelloWebServiceServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWebServiceServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWebServiceServer
     */
    @WebEndpoint(name = "HelloWebServiceServerImplPort")
    public HelloWebServiceServer getHelloWebServiceServerImplPort() {
        return super.getPort(new QName("http://hws.svc32.com/", "HelloWebServiceServerImplPort"), HelloWebServiceServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWebServiceServer
     */
    @WebEndpoint(name = "HelloWebServiceServerImplPort")
    public HelloWebServiceServer getHelloWebServiceServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hws.svc32.com/", "HelloWebServiceServerImplPort"), HelloWebServiceServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWEBSERVICESERVERIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOWEBSERVICESERVERIMPLSERVICE_EXCEPTION;
        }
        return HELLOWEBSERVICESERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
